- baseInfo:
    api_name: 新增商品
    url: http://localhost:8080/product/add
    method: POST
    header:
      Content-Type: application/json
  testCase:
    - case_name: 正常新增商品
      json:
        shopId: 1
        categoryId: 1
        productName: 测试商品
        productDescription: 这是一个测试商品
        price: 99.9
        stock: 100
        status: normal
        images: http://example.com/product.jpg
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'success' }
        - contains: { '$.json().info': '成功' }
    
    - case_name: 商品名称为空
      json:
        shopId: 1
        categoryId: 1
        productName: ""
        productDescription: 这是一个测试商品
        price: 99.9
        stock: 100
        status: normal
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'error' }
        - contains: { '$.json().info': '商品名称' }
    
    - case_name: 价格为负数
      json:
        shopId: 1
        categoryId: 1
        productName: 测试商品2
        productDescription: 这是一个测试商品
        price: -99.9
        stock: 100
        status: normal
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'error' }
        - contains: { '$.json().info': '价格' }
    
    - case_name: 库存为负数
      json:
        shopId: 1
        categoryId: 1
        productName: 测试商品3
        productDescription: 这是一个测试商品
        price: 99.9
        stock: -10
        status: normal
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'error' }
        - contains: { '$.json().info': '库存' }

- baseInfo:
    api_name: 根据ID查询商品
    url: http://localhost:8080/product/getProductById
    method: GET
    header:
      Content-Type: application/json
  testCase:
    - case_name: 正常查询商品
      params:
        id: 1
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'success' }
        - contains: { '$.json().data.productName': '测试商品' }
    
    - case_name: 查询不存在的商品
      params:
        id: 999999
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'error' }
        - contains: { '$.json().info': '商品不存在' }

- baseInfo:
    api_name: 更新商品信息
    url: http://localhost:8080/product/updateProductById
    method: PUT
    header:
      Content-Type: application/json
  testCase:
    - case_name: 正常更新商品
      json:
        bean:
          productName: 更新后的测试商品
          price: 159.9
          stock: 50
          productDescription: 这是更新后的商品描述
        id: 1
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'success' }
        - contains: { '$.json().info': '成功' }
    
    - case_name: 更新不存在的商品
      json:
        bean:
          productName: 不存在的商品
          price: 99.9
          stock: 100
        id: 999999
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'error' }
        - contains: { '$.json().info': '商品不存在' }

- baseInfo:
    api_name: 删除商品
    url: http://localhost:8080/product/deleteProductById
    method: DELETE
    header:
      Content-Type: application/json
  testCase:
    - case_name: 正常删除商品
      params:
        id: 2
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'success' }
        - contains: { '$.json().info': '成功' }
    
    - case_name: 删除不存在的商品
      params:
        id: 999999
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'error' }
        - contains: { '$.json().info': '商品不存在' }

- baseInfo:
    api_name: 分页查询商品列表
    url: http://localhost:8080/product/loadDataList
    method: GET
    header:
      Content-Type: application/json
  testCase:
    - case_name: 正常分页查询
      params:
        pageSize: 10
        pageNum: 1
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'success' }
        - contains: { '$.json().info': '成功' }
    
    - case_name: 按商店查询商品
      params:
        pageSize: 10
        pageNum: 1
        shopId: 1
      validation:
        - eq: { '$.status_code': 200 }
        - eq: { '$.json().status': 'success' }
        - contains: { '$.json().info': '成功' }
